services:
  bot:
    build: .
    volumes:
      - ./:/bot-bahamut
    environment:
      RUBOTY_NAME: "bahamut"
      ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
    command: bundle exec ruboty --load handlers.rb
    tty: true
