service: bot-bahamut
image: unasuke/bot-bahamut

servers:
  bot:
    hosts:
      - <%= ENV['KAMAL_SERVER_ADDRESS'] %>
    cmd: bundle exec ruboty --load handlers.rb
    proxy: false
    options:
      tty: true

primary_role: bot

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

ssh:
  user: ubuntu

env:
  clear:
    RUBOTY_NAME: bahamut
  secret:
    - DISCORD_TOKEN
    - ANTHROPIC_API_KEY
